project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: lab.qmd
      - href: projects.qmd
        text: Projects
      - href: Final.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

